import type maplibregl from 'maplibre-gl';
import type { CustomTheme } from '../../types/themes';

/** Maps each editable CustomTheme field to the (layer, paint property) it controls in the style generated by artistic-style.ts. Fields with no direct map layer (e.g. 'text', which only affects the DOM/canvas overlay text) are omitted — there's nothing to live-preview on the map for those. */
const FIELD_TO_LAYER_PAINT: Partial<Record<keyof Omit<CustomTheme, 'name' | 'description'>, { layer: string; paint: string }>> = {
	bg: { layer: 'background', paint: 'background-color' },
	water: { layer: 'water', paint: 'fill-color' },
	parks: { layer: 'park', paint: 'fill-color' },
	road_motorway: { layer: 'road-motorway', paint: 'line-color' },
	road_primary: { layer: 'road-primary', paint: 'line-color' },
	road_secondary: { layer: 'road-secondary', paint: 'line-color' },
	road_tertiary: { layer: 'road-tertiary', paint: 'line-color' },
	road_residential: { layer: 'road-residential', paint: 'line-color' },
	road_default: { layer: 'road-default', paint: 'line-color' },
	route: { layer: 'route-line', paint: 'line-color' },
};

/** Applies one field's color directly to the live map, for real-time feedback while dragging a color picker in the custom theme editor — no store write, no style regeneration. */
export function previewThemeField(map: maplibregl.Map | null, field: keyof Omit<CustomTheme, 'name' | 'description'>, colorValue: string): void {
	if (!map) return;
	const target = FIELD_TO_LAYER_PAINT[field];
	if (!target) return;
	if (!map.getLayer(target.layer)) return;
	try {
		map.setPaintProperty(target.layer, target.paint, colorValue);
	} catch {
		/* layer may be mid-transition during a style swap — the next real style load will pick up the saved value anyway */
	}
}
